"""add is_active to products

Revision ID: 11d9795f8da6
Revises: 9f8b06da2281
Create Date: 2026-06-20 18:11:49.633119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '11d9795f8da6'
down_revision: Union[str, None] = '9f8b06da2281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.alter_column('products', 'is_active', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_active')
    # ### end Alembic commands ###
