"""add_signature_image

Revision ID: 9f8b06da2281
Revises: d450f60aeea8
Create Date: 2026-06-18 19:32:07.704544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9f8b06da2281'
down_revision: Union[str, None] = 'd450f60aeea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('signature_image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'signature_image')
    # ### end Alembic commands ###
