"""add_show_gst_on_invoice_flag

Revision ID: d450f60aeea8
Revises: f68889b483d9
Create Date: 2026-06-18 19:03:07.782203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd450f60aeea8'
down_revision: Union[str, None] = 'f68889b483d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('show_gst_on_invoice', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'show_gst_on_invoice')
    # ### end Alembic commands ###
