"""add_invoice_settings_to_user

Revision ID: f68889b483d9
Revises: a1b2c3d4e5f6
Create Date: 2026-06-18 18:56:57.944638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f68889b483d9'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('business_address', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('business_phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('business_email', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('business_state', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('invoice_prefix', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('invoice_next_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'invoice_next_number')
    op.drop_column('users', 'invoice_prefix')
    op.drop_column('users', 'business_state')
    op.drop_column('users', 'business_email')
    op.drop_column('users', 'business_phone')
    op.drop_column('users', 'business_address')
    # ### end Alembic commands ###
